[package]
name = "concertino-amm"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.29"
anchor-spl = "0.29"
spl-token = { version = "3.3", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
name = "concertino_amm"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[lints.rust]
unexpected_cfgs = "allow"
